version: '3.8'

services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: payments
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: password123
    ports:
      - "8081:8081"
    volumes:
      - db_data:/usr/lib/mysql

volumes:
    db_data: